//resources

//for introScreen
import 'package:carousel_slider/carousel_controller.dart';
import 'package:ecommerce_app_firebase/models/product_model.dart';
import 'package:flutter/material.dart';

int currentPage = 0;
CarouselController carouselController = CarouselController();
dynamic person;

List viewPage = [
  {
    'Title': 'Order Your Food',
    'image': 'assets/images/stocks/1.png',
    'desc': 'Now you can order food any time right from your mobile.',
  },
  {
    'Title': 'Cooking Safe Food',
    'image': 'assets/images/stocks/2.png',
    'desc': 'We are maintain safety and We keep clean while making food.',
  },
  {
    'Title': 'Quick delivery',
    'image': 'assets/images/stocks/3.png',
    'desc': 'Orders your favourite meals will be immediately deliver',
  },
];

//for signInScreen
final GlobalKey<FormState> SignInKey = GlobalKey<FormState>();
TextEditingController emailController = TextEditingController();
TextEditingController passwordController = TextEditingController();
String? email;
String? password;
bool viewPassword = true;

//for loginScreen
final GlobalKey<FormState> logInKey = GlobalKey<FormState>();
TextEditingController emailControllerLog = TextEditingController();
TextEditingController passwordControllerLog = TextEditingController();
String? logEmail;
String? logPassword;
bool logViewPassword = true;

//for HomePage and Detail Page
List viewCategory = [
  {
    'id': 1,
    'name': 'All',
  },
  {
    'id': 2,
    'name': 'Fiction',
  },
  {
    'id': 3,
    'name': 'Psychology',
  },
  {
    'id': 4,
    'name': 'Finance',
  },
  {
    'id': 5,
    'name': 'Self-Help',
  },
];
List category = [
  {
    'id': 1,
    'name': 'Fiction',
    'img': '🍕',
  },
  {
    'id': 2,
    'name': 'Psychology',
    'img': '🍔',
  },
  {
    'id': 3,
    'name': 'Finance',
    'img': '☕️',
  },
  {
    'id': 4,
    'name': 'Selp-Help Books',
    'img': '🍦',
  },
];

List AllProducts = [
  products(
    id: 2,
    name: 'Brain Connections',
    category: 'Psychology',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/p1.png',
    quantity: 1,
    price: 329,
  ),
  products(
    id: 3,
    name: 'Public Finance',
    category: '️Finance',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/ff1.png',
    quantity: 1,
    price: 59,
  ),
  products(
    id: 4,
    name: 'Subtle Art',
    category: 'Self-Help',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/s1.png',
    quantity: 1,
    price: 129,
  ),
  products(
    id: 1,
    name: 'Out Last Summer',
    category: 'Fiction',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/fiction/f1.png',
    quantity: 1,
    price: 459,
  ),
  products(
    id: 2,
    name: 'Creative Brain',
    category: 'Psychology',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/p2.png',
    quantity: 1,
    price: 659,
  ),
  products(
    id: 4,
    name: 'Inner Healing',
    category: 'Self-Help',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/s2.png',
    quantity: 1,
    price: 259,
  ),
  products(
    id: 3,
    name: 'Power of Invest',
    category: 'Finance',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/ff2.png',
    quantity: 1,
    price: 69,
  ),
  products(
    id: 1,
    name: 'The Secrets',
    category: 'fiction',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/fiction/f2.png',
    quantity: 1,
    price: 699,
  ),
  products(
    id: 2,
    name: 'The Human Brain',
    category: 'Psychology',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/p3.png',
    quantity: 1,
    price: 269,
  ),
  products(
    id: 3,
    name: 'Corporate',
    category: 'Finance',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/ff3.png',
    quantity: 1,
    price: 69,
  ),
  products(
    id: 4,
    name: 'Zen',
    category: 'Self-Help',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/s3.png',
    quantity: 1,
    price: 29,
  ),
  products(
    id: 1,
    name: 'Mastermind',
    category: 'Fiction',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/fiction/f3.png',
    quantity: 1,
    price: 369,
  ),
  products(
    id: 1,
    name: 'Ink & Stars',
    category: 'Fiction',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/fiction/f4.png',
    quantity: 1,
    price: 569,
  ),
  products(
    id: 4,
    name: 'Anxity',
    category: 'Self-Help',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/s4.png',
    quantity: 1,
    price: 69,
  ),
  products(
    id: 3,
    name: 'More Money',
    category: 'Finance',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/ff5.png',
    quantity: 1,
    price: 99,
  ),
  products(
    id: 1,
    name: 'The Garden',
    category: 'Fiction',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/fiction/f5.png',
    quantity: 1,
    price: 999,
  ),
  products(
    id: 2,
    name: 'Human Brain',
    category: 'Psychology',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/p4.png',
    quantity: 1,
    price: 369,
  ),
  products(
    id: 4,
    name: 'Power',
    category: 'Self-Help',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/s5.png',
    quantity: 1,
    price: 69,
  ),
  products(
    id: 1,
    name: '''Dragon's mother''',
    category: 'Fiction',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/fiction/f6.png',
    quantity: 1,
    price: 859,
  ),
  products(
    id: 3,
    name: 'Shallow',
    category: 'Finance',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/ff6.png',
    quantity: 1,
    price: 19,
  ),
  products(
    id: 4,
    name: 'Alchemist',
    category: 'Self-Help',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/s6.png',
    quantity: 1,
    price: 99,
  ),
  products(
    id: 2,
    name: 'Typography',
    category: 'Psychology',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/p5.png',
    quantity: 1,
    price: 159,
  ),
  products(
    id: 2,
    name: 'Element Spritives',
    category: 'Psychology',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/p6.png',
    quantity: 1,
    price: 789,
  ),
  products(
    id: 3,
    name: 'Black freedom',
    category: 'Finance',
    description: 'This Book is a good book to read with it.',
    image: 'assets/images/stocks/ff4.png',
    quantity: 1,
    price: 79,
  ),
];

// for mcd modeling

List categories = [
  {'uuid': '1', 'libelle': 'Fiction', 'description': '🍦'},
  {'uuid': '2', 'libelle': 'Romance', 'description': '🍦'},
  {'uuid': '3', 'libelle': 'Psychology', 'description': '🍦'},
  {'uuid': '4', 'libelle': 'Geogrphie', 'description': '🍦'},
  {'uuid': '5', 'libelle': 'Mathematique', 'description': '🍦'},
  {'uuid': '6', 'libelle': 'Finance', 'description': '🍦'},
  {'uuid': '7', 'libelle': 'Medecine', 'description': '🍦'},
  {'uuid': '8', 'libelle': 'tSv', 'description': '🍦'},
  {'uuid': '9', 'libelle': 'Recherche', 'description': '🍦'},
  {'uuid': '11', 'libelle': 'Manga', 'description': '🍦'},
  {'uuid': '12', 'libelle': 'Drama', 'description': '🍦'},
  {'uuid': '13', 'libelle': 'Astrologie', 'description': '🍦'},
  {'uuid': '14', 'libelle': 'Physique', 'description': '🍦'},
  {'uuid': '15', 'libelle': 'Numerique', 'description': '🍦'},
  {'uuid': '16', 'libelle': 'Programmation', 'description': '🍦'},
  {'uuid': '17', 'libelle': 'Musique', 'description': '🍦'},
  {'uuid': '18', 'libelle': 'Piano', 'description': '🍦'},
  {'uuid': '19', 'libelle': 'Algebre', 'description': '🍦'},
  {'uuid': '20', 'libelle': 'Thermo', 'description': '🍦'},
  {'uuid': '21', 'libelle': 'Religions', 'description': '🍦'},
  {'uuid': '22', 'libelle': 'Inspiration', 'description': '🍦'},
  {'uuid': '23', 'libelle': 'Motivation', 'description': '🍦'},
  {'uuid': '24', 'libelle': 'Art', 'description': '🍦'},
  {'uuid': '25', 'libelle': 'Peinture', 'description': '🍦'},
  {'uuid': '26', 'libelle': 'Cuisine', 'description': '🍦'},
  {'uuid': '27', 'libelle': 'Coiffure', 'description': '🍦'},
  {'uuid': '28', 'libelle': 'Maintenance Informatiqque', 'description': '🍦'},
  {'uuid': '29', 'libelle': 'Vetements', 'description': '🍦'},
  {'uuid': '30', 'libelle': 'Dance', 'description': '🍦'},
  {'uuid': '31', 'libelle': 'Voyage', 'description': '🍦'},
  {'uuid': '32', 'libelle': 'Strategie', 'description': '🍦'},
  {'uuid': '33', 'libelle': 'Jeux', 'description': '🍦'},
  {'uuid': '34', 'libelle': 'Sport', 'description': '🍦'},
  {'uuid': '35', 'libelle': 'Affaire', 'description': '🍦'},
];

List groupe = [
  {
    'id': '1',
    'libelle': 'groupe 1',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '2',
    'libelle': 'groupe 2',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '3',
    'libelle': 'groupe 3',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '4',
    'libelle': 'groupe 4',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '5',
    'libelle': 'groupe 5',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '6',
    'libelle': 'groupe 6',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '7',
    'libelle': 'groupe 7',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '8',
    'libelle': 'groupe 8',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '9',
    'libelle': 'groupe 9',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '10',
    'libelle': 'groupe 10',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '11',
    'libelle': 'groupe 11',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '12',
    'libelle': 'groupe 12',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '13',
    'libelle': 'groupe 13',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '14',
    'libelle': 'groupe 14',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '15',
    'libelle': 'groupe 15',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '16',
    'libelle': 'groupe 16',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '17',
    'libelle': 'groupe 17',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '18',
    'libelle': 'groupe 18',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '19',
    'libelle': 'groupe 19',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '20',
    'libelle': 'groupe 20',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '21',
    'libelle': 'groupe 21',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '22',
    'libelle': 'groupe 22',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '23',
    'libelle': 'groupe 23',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '24',
    'libelle': 'groupe 24',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '25',
    'libelle': 'groupe 25',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '26',
    'libelle': 'groupe 26',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '27',
    'libelle': 'groupe 27',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '28',
    'libelle': 'groupe 28',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '29',
    'libelle': 'groupe 29',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '30',
    'libelle': 'groupe 30',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '31',
    'libelle': 'groupe 31',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '32',
    'libelle': 'groupe 32',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '33',
    'libelle': 'groupe 33',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '34',
    'libelle': 'groupe 34',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '35',
    'libelle': 'groupe 35',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '36',
    'libelle': 'groupe 36',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '37',
    'libelle': 'groupe 37',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '38',
    'libelle': 'groupe 38',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '39',
    'libelle': 'groupe 39',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '40',
    'libelle': 'groupe 40',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '41',
    'libelle': 'groupe 41',
    'description': '🍦',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
];

List actions = [
  {
    'uuid': '1',
    'libelle': 'action 1',
    'url': 'https//action 1',
    'methode': 'methode 1',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '2',
    'libelle': 'action 2',
    'url': 'https//action 2',
    'methode': 'methode 2',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '3',
    'libelle': 'action 3',
    'url': 'https//action 3',
    'methode': 'methode 3',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '4',
    'libelle': 'action 4',
    'url': 'https//action 4',
    'methode': 'methode 4',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '5',
    'libelle': 'action 5',
    'url': 'https//action 5',
    'methode': 'methode 5',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '6',
    'libelle': 'action 6',
    'url': 'https//action 6',
    'methode': 'methode 6',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '7',
    'libelle': 'action 7',
    'url': 'https//action 7',
    'methode': 'methode 7',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '8',
    'libelle': 'action 8',
    'url': 'https//action 8',
    'methode': 'methode 8',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '9',
    'libelle': 'action 9',
    'url': 'https//action 9',
    'methode': 'methode 9',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '10',
    'libelle': 'action 10',
    'url': 'https//action 10',
    'methode': 'methode 10',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '11',
    'libelle': 'action 11',
    'url': 'https//action 11',
    'methode': 'methode 11',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '12',
    'libelle': 'action 12',
    'url': 'https//action 12',
    'methode': 'methode 12',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '13',
    'libelle': 'action 13',
    'url': 'https//action 13',
    'methode': 'methode 13',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '14',
    'libelle': 'action 14',
    'url': 'https//action 14',
    'methode': 'methode 14',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '15',
    'libelle': 'action 15',
    'url': 'https//action 15',
    'methode': 'methode 15',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '16',
    'libelle': 'action 16',
    'url': 'https//action 16',
    'methode': 'methode 16',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '17',
    'libelle': 'action 17',
    'url': 'https//action 17',
    'methode': 'methode 17',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '18',
    'libelle': 'action 18',
    'url': 'https//action 18',
    'methode': 'methode 18',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '19',
    'libelle': 'action 19',
    'url': 'https//action 19',
    'methode': 'methode 19',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '20',
    'libelle': 'action 20',
    'url': 'https//action 20',
    'methode': 'methode 20',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '21',
    'libelle': 'action 21',
    'url': 'https//action 21',
    'methode': 'methode 21',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '22',
    'libelle': 'action 22',
    'url': 'https//action 22',
    'methode': 'methode 22',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '23',
    'libelle': 'action 23',
    'url': 'https//action 23',
    'methode': 'methode 23',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '24',
    'libelle': 'action 24',
    'url': 'https//action 24',
    'methode': 'methode 24',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '25',
    'libelle': 'action 25',
    'url': 'https//action 25',
    'methode': 'methode 25',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '26',
    'libelle': 'action 26',
    'url': 'https//action 26',
    'methode': 'methode 26',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '27',
    'libelle': 'action 27',
    'url': 'https//action 27',
    'methode': 'methode 27',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '28',
    'libelle': 'action 28',
    'url': 'https//action 28',
    'methode': 'methode 28',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '29',
    'libelle': 'action 29',
    'url': 'https//action 29',
    'methode': 'methode 29',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '1',
    'libelle': 'action 30',
    'url': 'https//action 30',
    'methode': 'methode 30',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '1',
    'libelle': 'action 31',
    'url': 'https//action 31',
    'methode': 'methode 31',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '1',
    'libelle': 'action 32',
    'url': 'https//action 32',
    'methode': 'methode 32',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '1',
    'libelle': 'action 33',
    'url': 'https//action 33',
    'methode': 'methode 33',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '1',
    'libelle': 'action 34',
    'url': 'https//action 34',
    'methode': 'methode 34',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '1',
    'libelle': 'action 35',
    'url': 'https//action 35',
    'methode': 'methode 35',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
];

List conversation = [
  {
    'id': '1',
    'envoyeur_id': 'envoyeur 1',
    'recepteur_id': 'recepteur 1',
    'groupe_id': 'groupe 1 ',
    'conversation': 'conversation 1',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '2',
    'envoyeur_id': 'envoyeur 2',
    'recepteur_id': 'recepteur 2',
    'groupe_id': 'groupe 2 ',
    'conversation': 'conversation 2',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '2',
    'envoyeur_id': 'envoyeur 2',
    'recepteur_id': 'recepteur 2',
    'groupe_id': 'groupe 2 ',
    'conversation': 'conversation 2',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '3',
    'envoyeur_id': 'envoyeur 3',
    'recepteur_id': 'recepteur 3',
    'groupe_id': 'groupe 3 ',
    'conversation': 'conversation 3',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '4',
    'envoyeur_id': 'envoyeur 4',
    'recepteur_id': 'recepteur 4',
    'groupe_id': 'groupe 4 ',
    'conversation': 'conversation 4',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '5',
    'envoyeur_id': 'envoyeur 5',
    'recepteur_id': 'recepteur 5',
    'groupe_id': 'groupe 5 ',
    'conversation': 'conversation 5',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '6',
    'envoyeur_id': 'envoyeur 6',
    'recepteur_id': 'recepteur 6',
    'groupe_id': 'groupe 6 ',
    'conversation': 'conversation 6',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '7',
    'envoyeur_id': 'envoyeur 7',
    'recepteur_id': 'recepteur 7',
    'groupe_id': 'groupe 7 ',
    'conversation': 'conversation 7',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '8',
    'envoyeur_id': 'envoyeur 8',
    'recepteur_id': 'recepteur 8',
    'groupe_id': 'groupe 8 ',
    'conversation': 'conversation 8 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '9',
    'envoyeur_id': 'envoyeur 9',
    'recepteur_id': 'recepteur 9',
    'groupe_id': 'groupe 9 ',
    'conversation': 'conversation 9 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '10',
    'envoyeur_id': 'envoyeur 10',
    'recepteur_id': 'recepteur 10',
    'groupe_id': 'groupe 10 ',
    'conversation': 'conversation 10 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '11',
    'envoyeur_id': 'envoyeur 11',
    'recepteur_id': 'recepteur 11',
    'groupe_id': 'groupe 11 ',
    'conversation': 'conversation 11 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '12',
    'envoyeur_id': 'envoyeur 12',
    'recepteur_id': 'recepteur 12',
    'groupe_id': 'groupe 12 ',
    'conversation': 'conversation 12 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '13',
    'envoyeur_id': 'envoyeur 13',
    'recepteur_id': 'recepteur 13',
    'groupe_id': 'groupe 13 ',
    'conversation': 'conversation 13 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '14',
    'envoyeur_id': 'envoyeur 14',
    'recepteur_id': 'recepteur 14',
    'groupe_id': 'groupe 14 ',
    'conversation': 'conversation 14 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '15',
    'envoyeur_id': 'envoyeur 15',
    'recepteur_id': 'recepteur 15',
    'groupe_id': 'groupe 15 ',
    'conversation': 'conversation 15 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '16',
    'envoyeur_id': 'envoyeur 16',
    'recepteur_id': 'recepteur 16',
    'groupe_id': 'groupe 16 ',
    'conversation': 'conversation 16 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '17',
    'envoyeur_id': 'envoyeur 17',
    'recepteur_id': 'recepteur 17',
    'groupe_id': 'groupe 17 ',
    'conversation': 'conversation 17 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '18',
    'envoyeur_id': 'envoyeur 18',
    'recepteur_id': 'recepteur 18',
    'groupe_id': 'groupe 18 ',
    'conversation': 'conversation 18 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '19',
    'envoyeur_id': 'envoyeur 19',
    'recepteur_id': 'recepteur 19',
    'groupe_id': 'groupe 19 ',
    'conversation': 'conversation 19 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '20',
    'envoyeur_id': 'envoyeur 20',
    'recepteur_id': 'recepteur 20',
    'groupe_id': 'groupe 20 ',
    'conversation': 'conversation 20 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '21',
    'envoyeur_id': 'envoyeur 22',
    'recepteur_id': 'recepteur 22',
    'groupe_id': 'groupe 22 ',
    'conversation': 'conversation 22',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '23',
    'envoyeur_id': 'envoyeur 23',
    'recepteur_id': 'recepteur 23',
    'groupe_id': 'groupe 23 ',
    'conversation': 'conversation 23 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '24',
    'envoyeur_id': 'envoyeur 24',
    'recepteur_id': 'recepteur 24',
    'groupe_id': 'groupe 24 ',
    'conversation': 'conversation 24 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '25',
    'envoyeur_id': 'envoyeur 25',
    'recepteur_id': 'recepteur 25',
    'groupe_id': 'groupe 25 ',
    'conversation': 'conversation 25 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '24',
    'envoyeur_id': 'envoyeur 24',
    'recepteur_id': 'recepteur 24',
    'groupe_id': 'groupe 24 ',
    'conversation': 'conversation 24 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '25',
    'envoyeur_id': 'envoyeur 25',
    'recepteur_id': 'recepteur 25',
    'groupe_id': 'groupe 25 ',
    'conversation': 'conversation 25 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '26',
    'envoyeur_id': 'envoyeur 26',
    'recepteur_id': 'recepteur 26',
    'groupe_id': 'groupe 26 ',
    'conversation': 'conversation 26 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '27',
    'envoyeur_id': 'envoyeur 27',
    'recepteur_id': 'recepteur 27',
    'groupe_id': 'groupe 27 ',
    'conversation': 'conversation 27 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '28',
    'envoyeur_id': 'envoyeur 28',
    'recepteur_id': 'recepteur 28',
    'groupe_id': 'groupe 28 ',
    'conversation': 'conversation 28 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '29',
    'envoyeur_id': 'envoyeur 29',
    'recepteur_id': 'recepteur 29',
    'groupe_id': 'groupe 29 ',
    'conversation': 'conversation 29 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '30',
    'envoyeur_id': 'envoyeur 30',
    'recepteur_id': 'recepteur 30',
    'groupe_id': 'groupe 30 ',
    'conversation': 'conversation 30 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '31',
    'envoyeur_id': 'envoyeur 31',
    'recepteur_id': 'recepteur 31',
    'groupe_id': 'groupe 31 ',
    'conversation': 'conversation 31 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '32',
    'envoyeur_id': 'envoyeur 32',
    'recepteur_id': 'recepteur 32',
    'groupe_id': 'groupe 32 ',
    'conversation': 'conversation 32 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '33',
    'envoyeur_id': 'envoyeur 33',
    'recepteur_id': 'recepteur 33',
    'groupe_id': 'groupe 33 ',
    'conversation': 'conversation 33 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '34',
    'envoyeur_id': 'envoyeur 34',
    'recepteur_id': 'recepteur 34',
    'groupe_id': 'groupe 34 ',
    'conversation': 'conversation 34 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'id': '35',
    'envoyeur_id': 'envoyeur 35',
    'recepteur_id': 'recepteur 35',
    'groupe_id': 'groupe 35 ',
    'conversation': 'conversation 35 ',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
];

List groupe_utilisateur = [
  {
    'id': '1',
    'groupe_id': 'groupe 1',
    'utilisateur_id': 'utilisateur 1',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '2',
    'groupe_id': 'groupe 2',
    'utilisateur_id': 'utilisateur 2',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '3',
    'groupe_id': 'groupe 3',
    'utilisateur_id': 'utilisateur 3',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '4',
    'groupe_id': 'groupe 4',
    'utilisateur_id': 'utilisateur 4',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '5',
    'groupe_id': 'groupe 5',
    'utilisateur_id': 'utilisateur 5',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '6',
    'groupe_id': 'groupe 6',
    'utilisateur_id': 'utilisateur 6',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '7',
    'groupe_id': 'groupe 7',
    'utilisateur_id': 'utilisateur 7',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '8',
    'groupe_id': 'groupe 8',
    'utilisateur_id': 'utilisateur 8',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '9',
    'groupe_id': 'groupe 9',
    'utilisateur_id': 'utilisateur 9',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '10',
    'groupe_id': 'groupe 10',
    'utilisateur_id': 'utilisateur 10',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '11',
    'groupe_id': 'groupe 11',
    'utilisateur_id': 'utilisateur 11',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '12',
    'groupe_id': 'groupe 12',
    'utilisateur_id': 'utilisateur 12',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '13',
    'groupe_id': 'groupe 13',
    'utilisateur_id': 'utilisateur 13',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '14',
    'groupe_id': 'groupe 14',
    'utilisateur_id': 'utilisateur 14',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '15',
    'groupe_id': 'groupe 15',
    'utilisateur_id': 'utilisateur 15',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '16',
    'groupe_id': 'groupe 16',
    'utilisateur_id': 'utilisateur 16',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '17',
    'groupe_id': 'groupe 17',
    'utilisateur_id': 'utilisateur 17',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '18',
    'groupe_id': 'groupe 18',
    'utilisateur_id': 'utilisateur 18',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '19',
    'groupe_id': 'groupe 19',
    'utilisateur_id': 'utilisateur 19',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '20',
    'groupe_id': 'groupe 20',
    'utilisateur_id': 'utilisateur 20',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '21',
    'groupe_id': 'groupe 21',
    'utilisateur_id': 'utilisateur 21',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '22',
    'groupe_id': 'groupe 22',
    'utilisateur_id': 'utilisateur 22',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '23',
    'groupe_id': 'groupe 23',
    'utilisateur_id': 'utilisateur 23',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '24',
    'groupe_id': 'groupe 24',
    'utilisateur_id': 'utilisateur 24',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '25',
    'groupe_id': 'groupe 25',
    'utilisateur_id': 'utilisateur 25',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '26',
    'groupe_id': 'groupe 26',
    'utilisateur_id': 'utilisateur 26',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '27',
    'groupe_id': 'groupe 27',
    'utilisateur_id': 'utilisateur 27',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '28',
    'groupe_id': 'groupe 28',
    'utilisateur_id': 'utilisateur 28',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '29',
    'groupe_id': 'groupe 29',
    'utilisateur_id': 'utilisateur 29',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '30',
    'groupe_id': 'groupe 30',
    'utilisateur_id': 'utilisateur 30',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '31',
    'groupe_id': 'groupe 31',
    'utilisateur_id': 'utilisateur 31',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '32',
    'groupe_id': 'groupe 32',
    'utilisateur_id': 'utilisateur 32',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '33',
    'groupe_id': 'groupe 33',
    'utilisateur_id': 'utilisateur 33',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '34',
    'groupe_id': 'groupe 34',
    'utilisateur_id': 'utilisateur 34',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
  {
    'id': '35',
    'groupe_id': 'groupe 35',
    'utilisateur_id': 'utilisateur 35',
    'rejoint_le': DateTime.now(),
    'quitte_le': DateTime.now(),
  },
];

List message = [
  {
    'id': '1',
    'message': 'message 1',
    'sujet_id': 'sujet 1',
    'utilisateur_id': 'utilisateur 1',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '2',
    'message': 'message 2',
    'sujet_id': 'sujet 2',
    'utilisateur_id': 'utilisateur 2',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '3',
    'message': 'message 3',
    'sujet_id': 'sujet 3',
    'utilisateur_id': 'utilisateur 3',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '4',
    'message': 'message 4',
    'sujet_id': 'sujet 4',
    'utilisateur_id': 'utilisateur 4',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '5',
    'message': 'message 5',
    'sujet_id': 'sujet 5',
    'utilisateur_id': 'utilisateur 5',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '6',
    'message': 'message 6',
    'sujet_id': 'sujet 6',
    'utilisateur_id': 'utilisateur 6',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '7',
    'message': 'message 7',
    'sujet_id': 'sujet 7',
    'utilisateur_id': 'utilisateur 7',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '8',
    'message': 'message 8',
    'sujet_id': 'sujet 8',
    'utilisateur_id': 'utilisateur 8',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '9',
    'message': 'message 9',
    'sujet_id': 'sujet 9',
    'utilisateur_id': 'utilisateur 9',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '10',
    'message': 'message 10',
    'sujet_id': 'sujet 10',
    'utilisateur_id': 'utilisateur 10',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '11',
    'message': 'message 11',
    'sujet_id': 'sujet 11',
    'utilisateur_id': 'utilisateur 11',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '12',
    'message': 'message 12',
    'sujet_id': 'sujet 12',
    'utilisateur_id': 'utilisateur 12',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '13',
    'message': 'message 13',
    'sujet_id': 'sujet 13',
    'utilisateur_id': 'utilisateur 13',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '14',
    'message': 'message 14',
    'sujet_id': 'sujet 14',
    'utilisateur_id': 'utilisateur 14',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '15',
    'message': 'message 15',
    'sujet_id': 'sujet 15',
    'utilisateur_id': 'utilisateur 15',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '16',
    'message': 'message 16',
    'sujet_id': 'sujet 16',
    'utilisateur_id': 'utilisateur 16',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '17',
    'message': 'message 17',
    'sujet_id': 'sujet 17',
    'utilisateur_id': 'utilisateur 17',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '18',
    'message': 'message 18',
    'sujet_id': 'sujet 18',
    'utilisateur_id': 'utilisateur 18',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '18',
    'message': 'message 18',
    'sujet_id': 'sujet 18',
    'utilisateur_id': 'utilisateur 18',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '19',
    'message': 'message 19',
    'sujet_id': 'sujet 19',
    'utilisateur_id': 'utilisateur 19',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '20',
    'message': 'message 20',
    'sujet_id': 'sujet 20',
    'utilisateur_id': 'utilisateur 20',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '21',
    'message': 'message 21',
    'sujet_id': 'sujet 21',
    'utilisateur_id': 'utilisateur 21',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '22',
    'message': 'message 22',
    'sujet_id': 'sujet 22',
    'utilisateur_id': 'utilisateur 22',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '23',
    'message': 'message 23',
    'sujet_id': 'sujet 23',
    'utilisateur_id': 'utilisateur 23',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '24',
    'message': 'message 24',
    'sujet_id': 'sujet 24',
    'utilisateur_id': 'utilisateur 24',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '25',
    'message': 'message 25',
    'sujet_id': 'sujet 25',
    'utilisateur_id': 'utilisateur 25',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '26',
    'message': 'message 26',
    'sujet_id': 'sujet 26',
    'utilisateur_id': 'utilisateur 26',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '27',
    'message': 'message 27',
    'sujet_id': 'sujet 27',
    'utilisateur_id': 'utilisateur 27',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '28',
    'message': 'message 28',
    'sujet_id': 'sujet 28',
    'utilisateur_id': 'utilisateur 28',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '29',
    'message': 'message 29',
    'sujet_id': 'sujet 29',
    'utilisateur_id': 'utilisateur 29',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '30',
    'message': 'message 30',
    'sujet_id': 'sujet 30',
    'utilisateur_id': 'utilisateur 30',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '31',
    'message': 'message 31',
    'sujet_id': 'sujet 31',
    'utilisateur_id': 'utilisateur 31',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '32',
    'message': 'message 32',
    'sujet_id': 'sujet 32',
    'utilisateur_id': 'utilisateur 32',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '33',
    'message': 'message 33',
    'sujet_id': 'sujet 33',
    'utilisateur_id': 'utilisateur 33',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '34',
    'message': 'message 34',
    'sujet_id': 'sujet 34',
    'utilisateur_id': 'utilisateur 34',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '35',
    'message': 'message 35',
    'sujet_id': 'sujet 35',
    'utilisateur_id': 'utilisateur 35',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
];

List permission = [
  {
    'uuid': '1',
    'role_id': 'role 1',
    'action_id ': 'action 1',
    'autorise': true,
  },
  {
    'uuid': '2',
    'role_id': 'role 2',
    'action_id ': 'action 2',
    'autorise': true,
  },
  {
    'uuid': '3',
    'role_id': 'role 3',
    'action_id ': 'action 3',
    'autorise': true,
  },
  {
    'uuid': '4',
    'role_id': 'role 4',
    'action_id ': 'action 4',
    'autorise': true,
  },
];
List role = [
  {
    'uuid': '1',
    'libelle': 'libelle 1',
    'description': 'description 1',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '2',
    'libelle': 'libelle 2',
    'description': 'description 2',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '3',
    'libelle': 'libelle 3',
    'description': 'description 3',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'uuid': '4',
    'libelle': 'libelle 4',
    'description': 'description 4',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
];
List sujet = [
  {
    'id': '1',
    'titre': 'titre 1',
    'sujet_id': 'sujet 1',
    'theme_id': 'theme 1',
    'auteur': 'auteur 1',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '2',
    'titre': 'titre 2',
    'sujet_id': 'sujet 2',
    'theme_id': 'theme 2',
    'auteur': 'auteur 2',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '3',
    'titre': 'titre 3',
    'sujet_id': 'sujet 3',
    'theme_id': 'theme 3',
    'auteur': 'auteur 3',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '4',
    'titre': 'titre 4',
    'sujet_id': 'sujet 4',
    'theme_id': 'theme 4',
    'auteur': 'auteur 4',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
];
List theme = [
  {
    'id': '1',
    'titre': '1',
    'theme_id': 'theme 1',
    'auteur': 'auteur 1',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '2',
    'titre': '2',
    'theme_id': 'theme 2',
    'auteur': 'auteur 2',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '3',
    'titre': '3',
    'theme_id': 'theme 3',
    'auteur': 'auteur 3',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
  {
    'id': '4',
    'titre': '4',
    'theme_id': 'theme 4',
    'auteur': 'auteur 4',
    'cree_le': DateTime.now(),
    'modifie_le': DateTime.now(),
  },
];
List utilisateur = [
  {
    'uuid': '1',
    'nom': 'nom 1',
    'prenom': 'prenom 1',
    'date_naiss': DateTime.now(),
    'sexe': 'feminin',
    'nom_utilisateur': 'nom_utilisateur 1',
    'cree_le': DateTime.now(),
    'roles': ['1', '2', '3'],
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '2',
    'nom': 'nom 2',
    'prenom': 'prenom 2',
    'date_naiss': DateTime.now(),
    'sexe': 'feminin',
    'nom_utilisateur': 'nom_utilisateur 2',
    'cree_le': DateTime.now(),
    'roles': ['1', '2', '3'],
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '3',
    'nom': 'nom 3',
    'prenom': 'prenom 3',
    'date_naiss': DateTime.now(),
    'sexe': 'feminin',
    'nom_utilisateur': 'nom_utilisateur 3',
    'cree_le': DateTime.now(),
    'roles': ['1', '2', '3'],
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '4',
    'nom': 'nom 4',
    'prenom': 'prenom 4',
    'date_naiss': DateTime.now(),
    'sexe': 'feminin',
    'nom_utilisateur': 'nom_utilisateur 4',
    'cree_le': DateTime.now(),
    'roles': ['1', '2', '3'],
    'modifie_le': DateTime.now()
  },
];
List livres = [
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '2',
    'libelle': 'titre2',
    'description': 'description2',
    'categories': ['34'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '3',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
  {
    'uuid': '1',
    'libelle': 'titre1',
    'description': 'description1',
    'categories': ['35'],
    'compteur_personnes': 20,
    'ajout_le': DateTime.now(),
    'modifie_le': DateTime.now()
  },
];
